# https://www.docker.com/blog/how-to-use-the-postgres-docker-official-image/
version: '3.8'

services:
  db:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=${PSQL_PASSWORD}
      - PGUSER=${PSQL_USER}
      - POSTGRES_DB=${PSQL_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5430:5432

  mageai:
    image: mageai/mageai
    container_name: mageai
    ports:
      - 6789:6789

  web_fe:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: web_be
    ports:
      - "3000:3000"
    env_file: .env

  db_be:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: db_be
    ports:
      - 4000:4000
    depends_on:
      - db

  execution_be:
    build:
      context: ./execution
      dockerfile: Dockerfile
    container_name: execution_be
    ports:
      - 5000:5000

  llm_be:
    build:
      context: ./llm
      dockerfile: Dockerfile
    container_name: llm_be
    ports:
      - 6000:6000
    env_file: .env
 
volumes:
  pgdata: